### ISSUE TITLE
Vis.ipynb

### ISSUE THREAD

**Issue by xingyu-cell** [hanjq17/GMN#5]
Hello author, I am now reproducing your visualization operation, I saved data.pkl in visualization, and when running vis.ipynb, KeyError: 919 appears, how to solve it? Hope to be able to help you, thank you very much

**Comment by hanjq17** [comment]
Hi,

You could try to see what has been saved into your data.pkl, e.g., what's the format and what are the keys. We could dive deeper into the problem on your side if you could provide more information.

**Comment by xingyu-cell** [comment]
Hello, author. Based on what you mentioned, I checked the data in data.pkl. Firstly, the data type is: <class 'dict'>. The keys in the dataset are: ['cfg_test', 'cfg_train', 'cfg_valid', 'charges_test', 'charges_train', 'charges_valid', 'edges_test', 'edges_train', 'edges_valid', 'loc_test', 'loc_train', 'loc_valid', 'vel_test', 'vel_train', 'vel_valid']. I have also provided their contents, types, and shapes. The type of cfg is a tuple, while the others are of type numpy.ndarray. For example, I want to access the vel_valid key, but an error occurs.I am now sending you my modified code, the run results, and the error messages, hoping to receive your help in reproducing the visualization. I apologize for taking your time on this. Thank you very much!

At 2024-11-01 05:00:10, "Jiaqi Han" ***@***.***> wrote:

Hi,

You could try to see what has been saved into your data.pkl, e.g., what's the format and what are the keys. We could dive deeper into the problem on your side if you could provide more information.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
gmnvis.zip (198.56M, 2024年11月17日 18:59 到期)
下载

**Comment by hanjq17** [comment]
Hi,

The idea is to save the prediction of the model as well as the input and the system configurations in `data.pkl`. It seems like you haven't saved the prediction of the model in your `data.pkl`. Moreover, the format is different from mine, so you may need to change the code in `vis.ipynb` in order to properly visualize. For instance, instead of indexing by the system id (like 919 I provided in the example), you need to use the keys like `loc_test' since you saved the data in this way.

Moreover I cannot get your files. Probably you need to put your files into some online storage and share the link.

Best

**Comment by xingyu-cell** [comment]
Hello，author.Based on your description, it’s possible that the issue occurred during the manual saving of data.pkl, or perhaps something was overlooked. I’ve included the details of the problem I encountered while running vis.ipynb at this [link](https://github.com/xingyu-cell/gmnvis.git) ，and I would greatly appreciate your assistance. Once again, I apologize for taking up your time.

**Comment by hanjq17** [comment]
Hi,

I checked your files and I find that `data.pkl` was not saved in the right way.

Your `data.pkl` is a collection of the **training data**. However, it should be the **inference result**, produced by a trained model.

The correct way is to save the inference results into `data.pkl`. For instance, you could save quantities like loc, loc_end, and loc_pred [here](https://github.com/hanjq17/GMN/blob/main/spatial_graph/main_motion.py#L255) and use them following the instructions in `vis.ipynb`.

**Comment by xingyu-cell** [comment]
Thank you so much! I've successfully replicated it, and my issue has been resolved. I might have more questions for you in the future.
